### Register
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Gaurav",
    "email": "gaurav4@gmail.com",
    "passsword": "test"
}

### login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "gaurav4@gmail.com",
    "passsword": "test"
}